## Theoretical

### What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow, an open-source machine learning framework, primarily deals with numerical computations involving multi-dimensional arrays known as tensors. While TensorFlow itself focuses on operations involving tensors, it doesn't provide a wide variety of traditional data structures like those found in general-purpose programming languages. However, it does have a few specialized data structures and abstractions that are crucial for building and training machine learning models. Here are some of them:

1. **Tensor**: Tensors are the fundamental data structure in TensorFlow. They are multi-dimensional arrays with a uniform data type. Tensors can represent various types of data, such as scalars, vectors, matrices, and higher-dimensional arrays. TensorFlow tensors are similar to NumPy arrays. Example:

   import tensorflow as tf

   scalar = tf.constant(5)              
   vector = tf.constant([1, 2, 3])      
   matrix = tf.constant([[1, 2], [3, 4]]) 

2. **Variable**: Variables are tensors with a mutable value. They are often used to store and update model parameters during training. Unlike constants, variables can be modified using operations like `assign()` or through automatic differentiation. Example:

   initial_value = tf.constant(0.5)
   variable = tf.Variable(initial_value)

3. **Placeholder**: In older versions of TensorFlow (prior to 2.0), placeholders were used to feed data into a TensorFlow computational graph. They were typically used in the context of building computational graphs for training. However, in TensorFlow 2.0 and later, placeholders have been replaced by eager execution and the `tf.data` API for data handling.

4. **SparseTensor**: A SparseTensor is used to efficiently represent tensors with a large number of elements that are mostly zero. It stores only the non-zero elements along with their indices, saving memory and computation time when dealing with sparse data.

   indices = tf.constant([[0, 0], [1, 2]])
   values = tf.constant([1, 2])
   shape = tf.constant([3, 4])
   sparse_tensor = tf.SparseTensor(indices, values, shape)

5. **RaggedTensor**: RaggedTensor is used to represent irregularly shaped tensors, where different rows can have different lengths. This is useful for sequences of varying lengths in natural language processing tasks.

   values = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])

6. **Dataset**: While not exactly a data structure, the `tf.data.Dataset` API is a crucial component for handling data in TensorFlow. It provides an abstraction for creating input pipelines for training and inference, enabling efficient data loading, preprocessing, and batching.

   dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

Remember that TensorFlow's primary focus is on numerical computations for machine learning, so the data structures it provides are geared towards supporting these tasks efficiently.

###  How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

In TensorFlow, both constants and variables are fundamental constructs used for creating and manipulating tensors within a computational graph. However, they serve different purposes based on their mutability and usage during training. Let's explore the differences between TensorFlow constants and variables with an example.

**TensorFlow Constant:**
A TensorFlow constant is a type of tensor with an unchanging value. Once you define a constant, its value remains the same throughout the execution of your program. Constants are typically used to represent fixed values or input data that don't need to be modified during computation. They are immutable.

import tensorflow as tf

#Define a constant
constant_tensor = tf.constant([1, 2, 3])

#You cannot modify the value of a constant
#This will raise an error: 'tensorflow.python.framework.errors_impl.FailedPreconditionError'
#constant_tensor.assign([4, 5, 6])

**TensorFlow Variable:**
A TensorFlow variable, on the other hand, is a tensor that holds a mutable value. Variables are commonly used to represent model parameters that need to be updated during training to minimize a loss function. They are crucial for training machine learning models as they allow the model's internal parameters to adapt based on the training data.

import tensorflow as tf
#Define a variable
initial_value = tf.constant(0.5)
variable = tf.Variable(initial_value)

#You can modify the value of a variable using the assign operation
new_value = tf.constant(1.0)
variable.assign(new_value)
print(variable.numpy())

In summary, the key differences between TensorFlow constants and variables are:

1. **Mutability**:
   - Constants are immutable; their values cannot be changed after creation.
   - Variables are mutable; their values can be changed using the `assign()` operation.

2. **Usage**:
   - Constants are used for fixed values or input data that remain unchanged during computation.
   - Variables are used to store and update model parameters during training.

3. **Role in Training**:
   - Constants do not play a direct role in model training; they represent static values.
   - Variables are essential for model training, as they store parameters that are updated through optimization algorithms.

Remember that TensorFlow 2.0 and later versions promote eager execution by default, which means you can use NumPy-like syntax and operations directly without explicitly creating computational graphs. This change affects how constants and variables are used in practice compared to earlier versions of TensorFlow.

###  Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

In [8]:
# Matrix Addition:
# Matrix addition involves adding two matrices element-wise to create a new matrix with the same dimensions. 
# This operation requires that the matrices being added have the same shape.

import tensorflow as tf

# Define two matrices
matrix_A = tf.constant([[1, 2], [3, 4]])
matrix_B = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result_matrix = tf.add(matrix_A, matrix_B)  

print("matrix addition:",result_matrix.numpy())


# Matrix Multiplication:
# Matrix multiplication (also known as matrix dot product) involves multiplying two matrices to produce a resulting matrix. 
# The number of columns in the first matrix must be equal to the number of rows in the second matrix.

import tensorflow as tf

# Define two matrices
matrix_A = tf.constant([[1, 2], [3, 4]])
matrix_B = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result_matrix = tf.matmul(matrix_A, matrix_B)

print("matrix multiplication",result_matrix.numpy())


# Element-wise Operations:
# Element-wise operations involve performing an operation on corresponding elements of two tensors (matrices or vectors) to....
# .....create a new tensor with the same shape. 
# Common element-wise operations include addition, subtraction, multiplication, division, etc.

import tensorflow as tf

# Define two matrices
matrix_A = tf.constant([[1, 2], [3, 4]])
matrix_B = tf.constant([[5, 6], [7, 8]])

# Perform element-wise addition
result_addition = matrix_A + matrix_B

# Perform element-wise multiplication
result_multiplication = matrix_A * matrix_B

print("elementwise addition",result_addition.numpy())
print("elementwise multiplication",result_multiplication.numpy())

matrix addition: [[ 6  8]
 [10 12]]
matrix multiplication [[19 22]
 [43 50]]
elementwise addition [[ 6  8]
 [10 12]]
elementwise multiplication [[ 5 12]
 [21 32]]


## Implementation

## Creating and Manipulating Matrices

#### Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display thevalues of matrix A.

In [9]:
import tensorflow as tf

matrix_A = tf.random.normal(shape=(3, 3))

print(matrix_A.numpy())

[[ 1.8219678  -0.29821756 -0.23450302]
 [ 2.3590455  -1.5827656  -0.7736521 ]
 [-1.69933     0.2379613   1.4506329 ]]


#### Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [10]:
import tensorflow as tf

matrix_B = tf.random.truncated_normal(shape=(4, 4))

print(matrix_B.numpy())

[[-0.2826818   0.22369117  0.917777   -0.37790024]
 [ 1.4952018   1.011636   -1.9968281  -0.33876252]
 [-0.28131124 -0.13701701 -0.10013592  0.60539   ]
 [ 0.49225715  0.12242389 -1.3957176  -0.31176543]]


#### Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C

In [11]:
import tensorflow as tf

mean = 3.0
stddev = 0.5
matrix_C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

print(matrix_C.numpy())

[[2.0314727 3.4842148]
 [2.5691702 2.5910575]]


#### Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [17]:
import tensorflow as tf

matrix_A = tf.random.normal(shape=(3, 3))
matrix_B = tf.random.truncated_normal(shape=(3, 3))

matrix_D = matrix_A + matrix_B

print("Matrix A:")
print(matrix_A.numpy())

print("\nMatrix B:")
print(matrix_B.numpy())

print("\nMatrix D (result of A + B):")
print(matrix_D.numpy())

Matrix A:
[[ 0.30264765  0.9154737  -1.3507128 ]
 [ 1.6939504  -0.9189398   0.8060413 ]
 [-1.1390458   0.38135812 -1.8817457 ]]

Matrix B:
[[ 1.0221665  -0.40379107 -0.11518381]
 [ 0.5687239   0.33284083 -0.20770413]
 [-0.5944292  -0.05901195 -0.69959503]]

Matrix D (result of A + B):
[[ 1.3248141   0.5116826  -1.4658966 ]
 [ 2.2626743  -0.586099    0.5983372 ]
 [-1.733475    0.32234615 -2.5813408 ]]


####  Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [19]:
import tensorflow as tf

matrix_C = tf.random.normal(shape=(2, 2), mean=3, stddev=0.5)
matrix_D = tf.random.normal(shape=(2, 2))  

matrix_E = tf.matmul(matrix_C, matrix_D)

print("Matrix C:")
print(matrix_C.numpy())

print("\nMatrix D:")
print(matrix_D.numpy())

print("\nMatrix E (result of C * D):")
print(matrix_E.numpy())

Matrix C:
[[3.6991436 2.4793825]
 [2.9533446 2.0174887]]

Matrix D:
[[ 1.0245514   0.12147891]
 [-1.0667708  -0.17251696]]

Matrix E (result of C * D):
[[1.14503    0.0216324 ]
 [0.8736553  0.01071808]]


### Performing Additional Matrix Operation

####  Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function

In [20]:
import tensorflow as tf

matrix_F = tf.random.uniform(shape=(3, 3))

print(matrix_F.numpy())

[[0.7243438  0.8968971  0.4920001 ]
 [0.36534595 0.56147194 0.74259067]
 [0.29401422 0.33168137 0.0642364 ]]


#### Calculate the transpose of matrix F and store the result in matrix G

In [21]:
import tensorflow as tf

matrix_F = tf.random.uniform(shape=(3, 3))

matrix_G = tf.transpose(matrix_F)

print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix G (transpose of F):")
print(matrix_G.numpy())


Matrix F:
[[0.8394525  0.87497926 0.660053  ]
 [0.04185617 0.6232101  0.19872844]
 [0.6876254  0.3849734  0.32923508]]

Matrix G (transpose of F):
[[0.8394525  0.04185617 0.6876254 ]
 [0.87497926 0.6232101  0.3849734 ]
 [0.660053   0.19872844 0.32923508]]


#### Calculate the elementDwise exponential of matrix F and store the result in matrix H

In [22]:
import tensorflow as tf

matrix_F = tf.random.uniform(shape=(3, 3))
matrix_H = tf.exp(matrix_F)

print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix H (element-wise exponential of F):")
print(matrix_H.numpy())

Matrix F:
[[0.16777349 0.17314565 0.5922115 ]
 [0.24210763 0.8454447  0.25873613]
 [0.299973   0.91616154 0.7693374 ]]

Matrix H (element-wise exponential of F):
[[1.1826687 1.1890392 1.8079823]
 [1.2739313 2.3290133 1.295292 ]
 [1.3498224 2.499677  2.1583357]]


####  Create a matrix I by concatenating matrix F and matrix G horizontally

In [23]:
import tensorflow as tf

matrix_F = tf.random.uniform(shape=(3, 3))
matrix_G = tf.random.uniform(shape=(3, 3))
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)

print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix G:")
print(matrix_G.numpy())

print("\nMatrix I (concatenated horizontally):")
print(matrix_I.numpy())

Matrix F:
[[0.5870298  0.331434   0.51992023]
 [0.43655682 0.25718713 0.75785935]
 [0.6866698  0.5581752  0.8253894 ]]

Matrix G:
[[0.4774828  0.5209544  0.3321303 ]
 [0.79016006 0.17130566 0.04359603]
 [0.7752714  0.6950946  0.7513977 ]]

Matrix I (concatenated horizontally):
[[0.5870298  0.331434   0.51992023 0.4774828  0.5209544  0.3321303 ]
 [0.43655682 0.25718713 0.75785935 0.79016006 0.17130566 0.04359603]
 [0.6866698  0.5581752  0.8253894  0.7752714  0.6950946  0.7513977 ]]


####  Create a matrix J by concatenating matrix F and matrix H vertically

In [24]:
import tensorflow as tf

matrix_F = tf.random.uniform(shape=(3, 3))

matrix_H = tf.exp(matrix_F)

matrix_J = tf.concat([matrix_F, matrix_H], axis=0)

print("Matrix F:")
print(matrix_F.numpy())

print("\nMatrix H (element-wise exponential of F):")
print(matrix_H.numpy())

print("\nMatrix J (concatenated vertically):")
print(matrix_J.numpy())

Matrix F:
[[0.80237055 0.02515936 0.9889418 ]
 [0.41004777 0.60735786 0.62033224]
 [0.17976975 0.37009203 0.16494024]]

Matrix H (element-wise exponential of F):
[[2.230823  1.0254785 2.688388 ]
 [1.5068898 1.8355751 1.8595457]
 [1.1969417 1.4478679 1.1793226]]

Matrix J (concatenated vertically):
[[0.80237055 0.02515936 0.9889418 ]
 [0.41004777 0.60735786 0.62033224]
 [0.17976975 0.37009203 0.16494024]
 [2.230823   1.0254785  2.688388  ]
 [1.5068898  1.8355751  1.8595457 ]
 [1.1969417  1.4478679  1.1793226 ]]
